services:

  app:
    build: .
    container_name: tcc_app
    depends_on:
      - db
      - mosquitto
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tcc
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: arthur
      MQTT_BROKER_URL: tcp://mosquitto:1883
    ports:
      - "8080:8080"

  db:
    image: mysql:8.0
    container_name: tcc_db
    environment:
      MYSQL_ROOT_PASSWORD: arthur
      MYSQL_DATABASE: inpark_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: tcc_mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
  mysql_data:
